<?php if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();

class testComponent extends CBitrixComponent
{

    public function executeComponent()
    {

        $this->doAction();
        $this->includeComponentTemplate();
        return parent::executeComponent(); // TODO: Change the autogenerated stub
    }

    public function doAction()
    {

        $elementId = $this->arParams['ELEMENT_CODE'];

        if (CModule::IncludeModule("iblock")) {
        $arElement = [];
        // Получаем отзыв по его ID
        $param = getIblockElement($elementId);
        $res = CIBlockElement::GetByID($elementId);
            if ($arElement = $res->Fetch()) {

            $this->arResult['SECTIONS'] = $arElement;      
            $this->arResult['SECTIONS']['company'] = $param['PROPERTIES']['company']['VALUE'];

            } else {
                echo "Отзыв не найден.";
            }

        }
    }
}